name: build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore **/*.csproj
      - name: Build
        run: dotnet build --configuration Release **/*.csproj --no-restore
      - name: Test
        run: dotnet test --configuration Release **/*Tests/*.csproj --no-build --verbosity normal
      - name: Pack
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet pack src/ConduitR.Abstractions/ConduitR.Abstractions.csproj -c Release -o artifacts
          dotnet pack src/ConduitR/ConduitR.csproj -c Release -o artifacts
          dotnet pack src/ConduitR.DependencyInjection/ConduitR.DependencyInjection.csproj -c Release -o artifacts
      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push artifacts/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
